# Generated by Django 3.2.3 on 2021-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financer', '0002_rename_user_financeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeuser',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
