# Generated by Django 3.2.3 on 2021-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financer', '0003_alter_financeuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
