# Generated by Django 3.2.3 on 2021-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financer', '0006_auto_20210601_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
